### ISSUE TITLE
VSCode extension: Useless inlay hints

### ISSUE THREAD

**Issue by MDLC01** [Myriad-Dreamin/tinymist#16]
### Describe the bug

Sometimes, inlay hints are displayed even when not necessary.

### To Reproduce

1. Create a new Typst file with the following contents.
    ```typ
    #let f(arg: none) = {}
    #f(arg: "hey")
    $ cal(M) $
    ```

2. Notice how hints appears after `"hey"` and `M`.

### Expected behavior

The hint after `"hey"` should not exist, because the this is a named parameter and the hint is therefore redundant.

The hint after `M` is useless ("body" does not convey any additional information), and it takes up horizontal space for nothing. I think inlay hints should not appear for arguments named `body` (and maybe some other highly generic names).

Additionally, I think there should be a way to disable inlay hints, as some people don't like this feature.

### Package/Software version

tinymist extension version: `v0.10.1`

**Comment by Myriad-Dreamin** [comment]
I'm going to remove the inlay hints on named arguments and add a flag to disable inlay hints dynamically.

>  I think inlay hints should not appear for arguments named body (and maybe some other highly generic names).

but I'm not sure how to process the positional arguments. It is not suitable to determine whether a name is general enough by, which highly depends on personal sense. That means if you don't like positional arguments, you should disable it totally.

**Comment by MDLC01** [comment]
I was mainly thinking about "body", since this is a very common argument name. But I understand why you wouldn't want to add a list of exceptions.

Maybe there should be a way to disable inlay hint only in math mode, though.

**Comment by ntjess** [comment]
Just for reference, here is vscode Python's approach to "partial" inlays:
![image](https://github.com/Myriad-Dreamin/tinymist/assets/23620506/6d10d181-d62c-4b12-a960-115b38dbaf5a)

But this is not helpful for Typst since all arguments are strictly positional or strictly keyword

Pycharm provides inlays for _literal_ positional arguments, assuming variable names are self-documenting. I'm a fan of this approach, but still has the problem for "body" arguments as mentioned in this issue

Perhaps if a function takes one argument, it is assumed to be obvious, but two or more positional, literal values will get the hints

I _don't_ think hard-coding assumptions based on the name is the way to go. There are several conventions (`it`, `body`, `content`, ...) and it may be _beneficial_ to inlay `body` when it comes after a different argument. I use the following for slides quite often:

```typst
let my-slide(title, body) = {...}
```

And it's nice to see that "title" comes before "body" in this simple example.

Just a few thoughts.

**Comment by MDLC01** [comment]
> Perhaps if a function takes one argument, it is assumed to be obvious, but two or more positional, literal values will get the hints

I like that!

**Comment by Myriad-Dreamin** [comment]
After thinking of it a bit, I can provides two special patterns of code to enable/disable individually:

+ `onSinglePositionalArgument`: when the function has only a single positional parameter.
+ `onContentBlockArgument`: when you use `content[]` grammar to pass the content arguments.

The inlay hints will not show if any pattern hits.

This is how to configure it. First, we have the simple switch to enable/disable/partially enable inlay hints.

```jsonc
{
  tinymist.inlayHints: "on" | "off" | "smart" // default: smart
}
```

I prefer to use `smart` rather than `partial`, because
+ I encourage you to use it, that sometimes help find bugs in your code.
+ `partial` are not descriptive, so I can change a name by my preference.

And then you can configure (like how you controls margins/paddings `x, y, left, right, top, bottom` of typst nodes) it by an object:

```jsonc
tinymist.inlayHints = {
  "onSinglePositionalArgument": "off",
  "onContentBlockArgument": "on",
  "rest": "on" // set default values to on or off
}
```

**Comment by MDLC01** [comment]
To be clear,
```json
{
  "tinymist.inlayHints": "smart"
}
```
is equivalent to
```json
{
  "tinymist.inlayHints": {
    "onSinglePositionalArgument": "off",
    "onContentBlockArgument": "on",
    "rest": "on"
  }
}
```
?

If so, I like the customizability, and the fact that you get a sensible behavior by default with `"smart"`.

**Comment by Myriad-Dreamin** [comment]
Yes. The string values of the `inlayHints` configuration are just equivalent to some object representations.
```jsonc
[
// the following two are equivalent:
{ "tinymist.inlayHints": "on" }
{ "tinymist.inlayHints": { rest: "on" } }
// the following two are equivalent:
{ "tinymist.inlayHints": "off" }
{ "tinymist.inlayHints": { rest: "off" } }
// the following two are equivalent:
{ "tinymist.inlayHints": "smart" }
{
  "tinymist.inlayHints": {
    "onSinglePositionalArgument": "off",
    // "onContentBlockArgument": "on",
    "rest": "on"
  }
}
]
```

**Comment by Myriad-Dreamin** [comment]
I have found another design question today, that the `on` enum may be confusing, because people probably don't get that when you `on` the "inlayHints", then all positions of "inlayHints" are shown.

An alternative enumerate values to replace `on | off | smart` is `all | never | smart` or `always | never | smart`.

**Comment by MDLC01** [comment]
I think `"always" | "never" | "smart"` is the clearer one.
