### ISSUE TITLE
Preview through LSP

### ISSUE THREAD

**Issue by knuesel** [Myriad-Dreamin/tinymist#357]
**Motivation**

Making "onType" browser preview and jump-to-source work in Helix and other editors that don't support VS Code extensions.

Currently I use https://github.com/tmistele/typst-lsp: a fork of typst-lsp that opens its own window to draw the preview, and also uses LSP to jump in the source when clicking somewhere in the preview. But it's rather experimental, the GUI is not very functional and it's not actively developed.

**Description**

* Add LSP settings to configure the browser preview (preview mode, host, open or not).
* Use LSP to send jump commands when clicking in the browser preview

**Examples/Questions**

I think it would make sense to have these settings separate from `exportPdf` (I would like to use both the live preview in the browser and compile to PDF on save).

Question: should this be implemented in the tinymist server, or as a new minimal LSP server just for preview? I guess in the tinymist server would be easier to use for most people. On the other hand a minimal LSP server would be nicer for those who only want the preview.

**Comment by Myriad-Dreamin** [comment]
Separating preview thread and LSP thread in different processes will double the memory usage on compilation. Tinymist has already integrated [typst-preview](https://github.com/Myriad-Dreamin/tinymist/tree/main/crates/typst-preview) since [v0.11.12](https://github.com/Myriad-Dreamin/tinymist/pull/352), which hasn't been used yet though.

To test it, you can check:

```bash
cargo run --bin tinymist -- preview main.typ
```

For minimal LSP, we can do some LSP wrapping on the preview server rather than publishing another binary. Some idea on [server mode](https://github.com/Myriad-Dreamin/tinymist/tree/main/crates/tinymist/src/server):

+ `lsp`: regular lsp.
+ `preview`: starts a preview server compatible with `typst-preview`.
+ `preview-lsp` (not implemented yet): starts a simple preview server, also accepting standard LSP messages.
+ `syntax-lsp` (not implemented yet): starts a syntax-only lsp server. you can have a better battery life. This is suitable for taking lecture notes in your class.


Note: we are encountering some bug in v0.11.12. If you are still on v0.11.11, please wait for v0.11.13 to have a stable release that fixes this bug.

**Comment by knuesel** [comment]
I managed to preview a file with `cargo run --bin tinymist -- preview main.typ` but it doesn't seem to work as an LSP server for helix. I guess that's expected?

Your ideas for minimal LSP sound great :)

**Comment by Myriad-Dreamin** [comment]
Since #368, we have:
- New command group:
    - `doStartPreview`: An internal command, starts a preview session and returns the exporting ports: `dataPlanePort` and `staticServerPort`.
    - `doKillPreview`: Kill a running preview unconditionally.
    - `scrollPreview`: editor informs preview panels to scroll.
- New notifications:
   - `tinymist/preview/scrollSource`: preview panels informs editor to scroll documents.
   - `tinymist/documentOutline`: informs changes of layout-stage document outline (compared with eval-stage document outline)
   - `tinymist/preview/dispose`: informs a closed preview session event.
   
This means that we can already use preview feature provided by lsp in neovim: you need to maintain the state at the client side and invoke commands.

I know these commands are likely unfriendly to clients such as helix, but I would like to close this "large issue". People can open more specific issues for requesting and discussing the design and implementation of preview feature furthermore.
