### ISSUE TITLE
Make `tinymist.rootPath` similarly flexible as `tinymist.outputPath`

### ISSUE THREAD

**Issue by SillyFreak** [Myriad-Dreamin/tinymist#401]
**Motivation**

I usually have multiple Typst documents in the same git repo/VS Code project. I also want to be able to use absolute paths in my imports (in principle, and I'm also working on a tool that would - at least for now - make this necessary). So my repo could look like this:

```
repo/
- document-a/
  - main.typ
  - sub.typ
- document-b/
  - main.typ
  - sub.typ
```

In the `main.typ` files, `#include "/sub.typ"` should work. Since `tinymist.rootPath` seems to default to `${workspaceFolder}` and only a "regular" path can be given, both documents can't at the same time be configured correctly.

**Description**

Allow using `$dir` in `tinymist.rootPath` (`$root` and `$name` would not be applicable). The current entry file would then determine what the root Path resolves to.

**Observation**

Interestingly, setting e.g. `"tinymist.rootPath": "${workspaceFolder}/does-not-exist"` makes this situation work currently: if the entry is outside the root, the root seems to be implicitly the location of the entry file.

**Comment by Myriad-Dreamin** [comment]
From my personal view, `#include "/sub.typ"` is an anti code pattern. Why don't you use relative path like `#include "sub.typ"` for the files in the same directory?

> Allow using $dir in tinymist.rootPath ($root and $name would not be applicable). The current entry file would then determine what the root Path resolves to.

It could be done while I'm not sure whether it can be as flexible as the outputPath. What can we do when we have `$dir`? I afraid that we can only set the `rootPath` to either a concrete path or `$dir`. The configuration like `$dir/..` or `/abc/$dir` doesn't make sense.

>Interestingly, setting e.g. "tinymist.rootPath": "${workspaceFolder}/does-not-exist" makes this situation work currently: if the entry is outside the root, the root seems to be implicitly the location of the entry file.

You've hacked my code😄. They are called rootless documents (may have better term to refer them), which are usually used when you are opening some typst source files directly. The rootless documents are compiled with a minimal directory that contains the doc as the root, i.e. the parent directory.

---

What about mentioning in documentation that one can set the `rootPath` to `-`, so that tinymist will make documents rootless with this configuration? I may not change any code but only update the document and see how our design will go.

**Comment by SillyFreak** [comment]
> From my personal view, `#include "/sub.typ"` is an anti code pattern. Why don't you use relative path like `#include "sub.typ"` for the files in the same directory?

I broadly agree, but I'm using that path not _just_ to resolve inside Typst, I also `typst query` it. In Typst, a path is relative to the file it appears in, but after querying I don't know what that file was. So if I write `#image("foo.png")` inside `sub/sub.typ`, I won't know to resolve it to `sub/foo.png`. I hope that the resources proposal will eventually help with this, but until then it would be nice if absolute paths could be made to work in that way.

> What about mentioning in documentation that one can set the `rootPath` to `-`, so that tinymist will make documents rootless with this configuration?

That works right now? Nice! I think documenting this should be enough. Using anything else than just `$dir` would probably not work for most documents anyway, so configuring VS Code globally would not help much. And in projects with special needs, workspace-wide settings would probably not have as much need for `$dir`.

One use case for `$dir/..` I can imagine is packages that contain tests: `tests/foo.typ` should be able to access `src/lib.typ`. But that's just `${workspaceFolder}` anyway, which would work better for that case.

> You've hacked my code 😄

Btw, I realized that because I often have multiple folders opened in a single VS Code workspace. Tinymist then seems to use the first one as the root, so all files in other folders are rootless! That made analyzing my actual issue more fun :sweat_smile: I can file a separate issue about that later.

**Comment by Myriad-Dreamin** [comment]
> I also typst query it.

I start to know your scenario quickly, then keeping using absolute paths does make sense.

> Tinymist then seems to use the first one as the root, so all files in other folders are rootless!

Okay, you can create a separated issue and I will make it work then. Tinymist has been aware of multiple roots and leave some design space but haven't make any progress on them because of need of extra efforts. The reason is simple to dead: I haven't seen any user reporting it so I view it as a less-frequently-used feature, and I personally don't open multiple folders in a workspace 👻.

**Comment by SuperKenVery** [comment]
I would vote for relative path too, I can't reference workspace root in config in zed. Even allowing "$dir" should help 😄
