### ISSUE TITLE
[VSCode] Support drag and drop of files (pdf and images) into the typst editor

### ISSUE THREAD

**Issue by LasseRosenow** [Myriad-Dreamin/tinymist#508]
**Motivation**

Writing function to include images etc. is tiresome.

**Description**

VSCode allows to transform the drag and drop behavior for different file types into the code editor.
The markdown extension already supports this:
- You can take a image file and drag it with your mouse into a markdown file.
- The text that is pasted into the markdown file then becomes the correct markdown code to include the image.
- For more information see [here](https://code.visualstudio.com/docs/languages/markdown#_inserting-images-and-links-to-files)

It would be amazing if we could have this feature for typst as well.

For example to drag an image into a typst file results in:
```typst
#image("path_to_image.jpg")
```

Or dragging a typst file into another typst file results int:
```typst
#include "path_to_typst_file.typ"
```

**Comment by Myriad-Dreamin** [comment]
It is great to have a integrated drag-and-drop function into tinymist. This is because we can customize not only behaviors of dragging and dropping images, but any files: by generating "calls to typst's read functions". But it is marked as low priority since you can reuse some efforts from other extensions, For example, [vscode-paste-image](https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image). This also means someone can adapt the code from that extensions to tinymist to allow better integration with typst.

----

The old idea in mind:

supports by builtin readers:

+ drop images (.jpg, .png, .svg, etc.) -> generate `image("path.img")`.
+ drop web urls -> ask and download images and generate `image("assets/path.img")`.
+ drop typst source files -> `#include "path.typ"` and change select to `#include` to help user change to `#import` quickly if they would like to.

supports by packages:

+ drop webp (not supported by typst) -> generate `#grayscale-image("path.webp")` (supported by [@preview/grayness](https://typst.app/universe/package/grayness))
+ drop markdown files -> `#cmarker.render(read("path.md"))` (supported by [@preview/cmark](https://typst.app/universe/package/cmarker))
+ drop latex files -> `#mitex(read("path.tex"))` (supported by [@preview/mitex](https://typst.app/universe/package/mitex))

---

Since it is not a core functionality, I think it is not hard to be contributed by anyone.

**Comment by purpl3F0x** [comment]
Hello, is pasting an image form clipboard also supported ?

**Comment by Myriad-Dreamin** [comment]
No, considering there are many mime types to handle, we only support drag and drop files first. But it is easy to extend this to access png images in the data transfer object. In short, there are many mime type to handle:

- [x] text/plain (url), file scheme
- [ ] text/plain (url), http/https scheme
- [ ] text/markdown
- [ ] text/x-tex
- [ ] image/png
- [ ] image/jpeg
- [ ] image/bmp
- [ ] image/svg+xml
- [ ] image/webp

**Comment by purpl3F0x** [comment]
I think it would be good, to at least have support for png files (like the markdown plugin), since you can't drag 'n drop a screenshot. 
(Although maybe it needs a separate issue)

**Comment by NoamDev** [comment]
@Myriad-Dreamin do we need to open a new issue for paste-image functionality?

**Comment by Myriad-Dreamin** [comment]
Sure.
