### ISSUE TITLE
[Feat Request] Project level configuration

### ISSUE THREAD

**Issue by Eric-Song-Nop** [Myriad-Dreamin/tinymist#530]
**Motivation**

It seems that whenever I restart the Neovim, I need to re-pin the main file, thus I hope that tinymist can have some sort of project level configuration.

**Description**

`tinymist` can read some project level configuration file, either `typst.toml` or other private configuration file, to determine stuffs like main file, root_dir, exclude file, compilation arguments, or other configurations. For now, some editors can handle some of them, but it might be good to be handled by `tinymist` to make it more corss-editor. 

**Examples/Questions**

not really any good examples for now

**Comment by Myriad-Dreamin** [comment]
From discussion, the configuration should be in `typst.toml`, and it can be not hod reloaded in first implementation. A minimal setting is only allow a single entry:
```toml
[[tinymist.input]]
entry = "project/main.typ"
```
For auto pinning: when you are seeing some file is related to this main file, the main file is used, otherwise it is unpinned and set the seeing file implicitly. This has lower priority than explicit pin. How do you think of it?

**Comment by Eric-Song-Nop** [comment]
Close as this discussion is moved to another issue
