### ISSUE TITLE
Clicking on preview opens a new window when working with multiple typst files

### ISSUE THREAD

**Issue by ziiirozone** [Myriad-Dreamin/tinymist#534]
**Describe the bug**
Hello !
I'm currently working with vs code on two different typst files, which I both have previews of. For the sake of explainations I'll number them file 1, file 2 & preview 1, preview 2. When I interact with file 1 and click on a word in preview 1 everything works as expected, but when I click on a word in preview 2, a new window with file 2 opens with the cursor on the word I clicked on. I now have 2 windows with file 2 open. When I double click on a word of preview 2 it seems to remember the first instance of file 2 and goes back to it. This makes working on multiple typst files quite difficult.

VSCode version :
```plain
Version: 1.92.1 (user setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

tinymist version 0.11.19

**Comment by Myriad-Dreamin** [comment]
The opening to new window function usually works well when the layout simply looks like following:

![image](https://github.com/user-attachments/assets/cdb69410-0054-4b7d-a095-94cd87707361)

But thing goes worse rapidly in other layouts, and we don't know how many layouts we should adapt to. I believe this is likely a twist to tune for previewing, and it is not quite related to tinymist's core function. The current algorithm is used here:

https://github.com/Myriad-Dreamin/tinymist/blob/68911d91cbaea2e9fb91f33df3d803b5b433ee41/editors/vscode/src/preview.ts#L684

https://github.com/Myriad-Dreamin/tinymist/blob/68911d91cbaea2e9fb91f33df3d803b5b433ee41/editors/vscode/src/util.ts#L24-L33

**Comment by ziiirozone** [comment]
I have no knowledge on how vs. code works or even how to program in typescript, but wouldn't it be possible to loop over each editor until one is found with a title matching that of the preview ?

**Comment by memeplex** [comment]
I'm seeing this quite frequently too. I'm trying to find some recipe in order to reproduce it in a more reliable fashion, still to no avail. By now I do can say that:

- Sometimes it happens even in the basic layout described above, but it might be that this is after having opened another previews (and then closed them), or because of having other files at the left group, or some of them being typ files, IDK, I can say it happens quite often but I still haven't found the pattern.

- Usually, when this happens, I close the just opened dup tab, interact with the original one (just click on the editor or scroll a bit) and then the preview gets aware of this file again. But after that I might scroll the preview and click at another location and a bogus tab is opened one more time. It's quite random.

**Comment by memeplex** [comment]
Ok, here's a reliable way to make it happen:

1. Create a project
2. Add a simple test.typ file with some content
3. Open the preview
4. Initalize git for the project
5. From source control open the diff tab for the file
6. Click the preview

At that point you should have:

- Group 1:
  - test.typ
  - test.typ diff
- Group 2:
  - test.typ preview
  - test.typ dup

<img width="1235" alt="image" src="https://github.com/user-attachments/assets/06a699d0-87c9-4d8a-838f-248749349406">

**Comment by memeplex** [comment]
I'm still seeing this a lot with the simple two pane layout described above. The reproduction steps I provided still work, although this happens in many other circumstances.
