### ISSUE TITLE
Rename/move files in vscode and automatically update links

### ISSUE THREAD

**Issue by pricklygorse** [Myriad-Dreamin/tinymist#542]
**Motivation**

Moving or naming a file in vscode file explorer breaks links within documents. It would be great if the links could be automatically updated. 

For example renaming a image file would automatically update links within `#image()` to the new location across the project.

This is a feature included in vscode when editing markdown files. It is disabled by default, but can be set to prompt first or update files automatically.

**Comment by Myriad-Dreamin** [comment]
The first PR updates import paths when renaming source files. We still don't support to handle rename image requests, as we don't have analyzer that identifies link in the document, which is not quite easy. Since we have made some progress on it, we can open anther feature request (issue) and update descriptions.
