### ISSUE TITLE
Simplify adding new lines

### ISSUE THREAD

**Issue by glyn** [Myriad-Dreamin/tinymist#584]
**Motivation**

I'd like to be able to enter new lines into Typst source by hitting "return". Currently, I have to resort to using the shift key with "return" and in some situations not even that works.

**Description**

The "return" key should always add a new line, like in most other editors.

**Examples/Questions**

I'm probably missing something in the design of Typst or the plugin. I would have raised this issue as a discussion if discussions were enabled.

**Comment by Enter-tainer** [comment]
sorry but i dont really get it why hitting enter doesnt add a newline. could you describe current behavior?

**Comment by glyn** [comment]
I tried reproducing the behaviour on macOS using vscode 1.92.2 and TinyMist v0.11.20, but the enter/return key worked perfectly. I'll go to my Linux box and try again...

**Comment by glyn** [comment]
Ok, on arch linux 6.10.6 with vscode 1.92.1 and TinyMist v0.11.20, I tried editing the same typst source file as previously and the enter/return key again worked perfectly. Trying to work out what went wrong originally...

**Comment by glyn** [comment]
I tried uninstalling TinyMist, re-starting vscode, and re-installing TinyMist and then editing the source file without restarting vscode, just in case that caused the original behaviour, but, no, it again worked perfectly.

For the record, the behaviour I was seeing was that the enter/return key acted dead - nothing happened when it was pressed. With some cursor positions shift+enter gave the expected bevahiour (inserted a new line at the cursor), but in other positions, no modifiers seemed to enable a new line to be entered and I had to resort to cut'n'paste and various other tricks to get new lines into the correct positions. All very strange, but since  I can't reproduce the behaviour, let's close this issue.

**Comment by Myriad-Dreamin** [comment]
The <kbd>Enter</kbd> key will be affected by `onEnter` API in https://github.com/Myriad-Dreamin/tinymist?tab=readme-ov-file#features. The API will insert some extra characters for you, like adding line comment prefix for you automatically. I considered added an option to disable it, but feel it is not great as we usually expect `onEnter` to always simply work uniformly for all.

On the other hand, `onEnter` will not work if lsp doesn't response you in background or it is just crashed. @glyn, you could note it in log when you find it is badly working again. Btw, this is the first bug report about `onEnter` since recent months of the feature released. I thus think of it will serve you almost perfectly.
