### ISSUE TITLE
How do you do live preview with tinymist in neovim?

### ISSUE THREAD

**Issue by kdog3682** [Myriad-Dreamin/tinymist#730]
The GitHub repo for https://github.com/Enter-tainer/typst-preview says the live server preview functionality has been incorporated into tinymist. 

I haven't been able to find this option on any of the docs.

Any help would be much appreciated. Thank you.

**Comment by Myriad-Dreamin** [comment]
https://github.com/chomosuke/typst-preview.nvim

**Comment by kdog3682** [comment]
Ah, I see!

Just curious, Does this mean there will be two separate instances of tinymist running? One for tinymist, and one for the typst-preview?

**Comment by Myriad-Dreamin** [comment]
> Does this mean there will be two separate instances of tinymist running? One for tinymist, and one for the typst-preview?

Yes, since there is no client-side language plugin, some editor-dependent features, e.g. the preview feature are limited. typst-preview.nvim just uses tinymist as a **cli** rather than a language **server**.

If one is going to make such a plugin for neovim, they can check [editors/vscode/src/features/preview.ts](https://github.com/Myriad-Dreamin/tinymist/blob/main/editors/vscode/src/features/preview.ts), which holds preview state and communicate with the language server on behalf of the editor for preview panel reactions.
