### ISSUE TITLE
Complete field accesses by type information

### ISSUE THREAD

**Issue by Eric-Song-Nop** [Myriad-Dreamin/tinymist#985]
**Motivation**

Tinymist should be able to get completion information from the type check information, instead of only the value of a variable.

**Description**

Type inference in Tinymist might provide more info than the value info from Typst, thus we could benefit from it for autocomplete to provide for information for completion, especially for field access completion

**Examples/Questions**
```typst
/// Function
///
/// - dic (dictionary, float): The argument dic
/// - val (string): 2nd arg
/// -> float
#let func(
  dic: (:),
  val: "",
) = return dic.|
```

For now, I believe no completion info can is provided from tinymist, while it could get the type of `dic` and provide field completion.

```typst
/// Function
///
/// - dic (dictionary, float): The argument dic
/// - val (string): 2nd arg
/// -> float
#let func(
  dic: (:),
  val: "",
) = return dic.|

#func(dic: (1, 2, 3))
```
While in this case, now it will complete as if `dic` is of value `(1, 2, 3)`, while the proper way might still be complete as (dictionary, float).

**Comment by Myriad-Dreamin** [comment]
Could you add some examples and ping me?

Btw, we are moving completion function from the old AST matchers (borrowed from typst-ide) to new unified infra:

https://github.com/Myriad-Dreamin/tinymist/blob/5747dd6ba623e5413fbd44f4ea64089e8a4eff00/crates/tinymist-query/src/upstream/complete.rs#L45-L53

The new infra (`complete_type_and_syntax`) will look like this:

```rs
fn complete_type_and_syntax(node: &LinkedNode) {
  let syntax_targets = match_syntax_targets(node); // P0, currently it is get_check_target
  let ctx = CompletionContext::new(..);
  
  // P1, Gets `ctx.pre_completion_items` cache if we can safely reuse them.
  if !ctx.load_cached_completion(node, syntax_targets) {
    for target in syntax_targets {
    
      // P2, Matches mode, syntax, ty, and create filter for each target on current cursor
      let mode = interpret_mode_at(target);
      let syntax = surrounding_syntax(target);
      let ty = type_check(target);
      let filter = create_filter(mode, syntax, ty);
      let tripple = CompletionTripple(mode, syntax, ty, filter);

      // P3, Gets associated items with filter.
      ctx.target_completion(tripple); // field accesses, import items, fonts, packages etc.
      ctx.scope_completion(tripple); // items accessible in current scope
      ctx.type_completion(tripple);
      ctx.snippet_completion(tripple); // semantic-aware snippets
    }
    
    ctx.store_completion_cache(node, syntax_targets);
  }
      
  // P4, Calculates how we apply `ctx.pre_completion_items` according to syntax
  for item in ctx.pre_completion_items {
    let range = calculate_range(node, item):
    let item = ctx.enrich_item(node, range, item);
    ctx.complete_(item, target, range);
  }
  
  ctx.completions
}
```

Description:
- first, P0: it uses new AST matchers to extract targets to complete. The new AST matchers are shared across analyzers.
- second, P1: if user is requesting same set of completion items, it loads cache quickly and goto P4.
- third, P2: it identifies the completion triple per target:
  - mode: the interpreting mode of the target, e.g. `code`, `markup`, `comment`, ...
  - syntax: the syntax pattern of the target, e.g. `ImportList`, `ShowTransform`.
  - type: given a target, check and give a type.
- forth, P3: query and filter items based on the triple. In the pseudo-code, four kind of items are calculated.
- fifth, P4, adjust items to fit in current code because user might change the cursor and ranges are changed accordingly.

Example triples to identify:
```typ
#import "..": | // InterpretMode::Code, SurroundingSyntax::ImportList, Ty::Any
// Only function accepting the raw is appliable to this show rule
#show raw: | // InterpretMode::Code, SurroundingSyntax::ShowTransform, Ty::Func(Element(raw), ..) -> Content
#| // InterpretMode::Code, SurroundingSyntax::HashExpr, Ty::Any
#a.b.|.d // InterpretMode::Code, SurroundingSyntax::FieldAccess(a.b), Ty::Any
@| // InterpretMode::Markup, SurroundingSyntax::Reference, Ty::ContentLabel
#cite(|) // InterpretMode::Code, SurroundingSyntax::Label, Ty::CiteLabel
```

**Comment by Eric-Song-Nop** [comment]
@Myriad-Dreamin I added an example here, I believe the current completion as least filed access completion is totally based on the `value`, while in many cases it is empty, which is much less powerful than tinymist's type inferencer.

**Comment by Eric-Song-Nop** [comment]
While completion based on value might still useful for field access completion as it contains all the keys of the dictionary, while `Ty` does(might) not have such info.

**Comment by Myriad-Dreamin** [comment]
Ignoring the underlying implementation details, it should refer to complete according to the result of either static analysis (by type) or dynamic analysis (by value).

Ideally, we should have both to get completion items as many as possible. For performance consideration, we should run dynamic analysis as least as possible because it is super expensive in regard to CPU and RAM usage. This also applies when we concern about the power efficiency. I'm not 100% sure, but we can test the power usage once we have the syntax-only server (which forbids `typst::trace` or even `typst::compile` in the language server).

I suggest we change the issue to "Complete field accesses by type information" to narrow down the problem to solve.
